### ISSUE TITLE
Question: What hook to use in the Vue case?

### ISSUE THREAD

**Issue by erip2** [archfz/vh-sticky-table-header#2]
Hi there!

I'm trying to add your package to my Vue project, but I'm not sure in what lifecycle method to put it. I see the code for React uses `useLayoutEffect`, but it seems that there isn't an equivalent of it in Vue (although I'm new to Vue).

Do you know how this can be used in a Vue project?

Thanks!

**Comment by archfz** [comment]
I did not use vue, so I cannot give you a definite answer. `useEffect` might also suffice in react, so maybe this can help: https://stackoverflow.com/questions/70072176/vue-3s-equivalent-to-useeffect-react

If you figure out how to use this package in vue, it would be nice if you added some instructions in readme.

**Comment by archfz** [comment]
Closing as of https://github.com/archfz/vh-sticky-table-header/pull/5
