### ISSUE TITLE
Sticky header horizontal scroll position bugged since 1.3

### ISSUE THREAD

**Issue by finkrer** [archfz/vh-sticky-table-header#3]
Apparently we broke stuff last time, oops.

To reproduce:
1. Use the official sandbox from readme, update library to 1.3.1
2. Scroll down until the header sticks
3. Scroll the table right
4. Scroll back up until the header unsticks
5. Scroll the table left
6. Scroll back down until the header sticks

Expected: clone header stays in the same position (works like that without updating the library)

Actual: clone header jumps to the position it was in when it was sticky last time, leaving the header and the columns misaligned

**Comment by archfz** [comment]
Fixed in 1.4.0
