### ISSUE TITLE
When clicking on header, table scrolls up

### ISSUE THREAD

**Issue by julianklumpers** [archfz/vh-sticky-table-header#6]
Hi,

Cool lib, exactly what i was looking for. 
However, when you click on the table header the page scrolls to the top of the table, is there some way to prevent this? Because we have sorting functionality on the headers.

This behavior is also in the [codesandbox](https://codesandbox.io/s/vh-sticky-table-header-demo-euykw?file=/src/TableWithStickyHeader.tsx&resolutionWidth=630&resolutionHeight=675) demo

**Comment by archfz** [comment]
That is what the scroll up functionality tries to achive. In essence we try to replicate the click on the same position on the original header, since the cloned header doesn't have the click handlers.

**Comment by julianklumpers** [comment]
Ok, i understand, is there a way to get around this? and have the click functionality on the headers without scrolling up?

**Comment by archfz** [comment]
We need to check don't remember if it is done manually the scroll, or automatically by the click replication, or if it is manually done but it is required for the click to work.

**Comment by julianklumpers** [comment]
I might have a solution to this, will test it and make a PR if it works.

**Comment by jjylha** [comment]
We also have some checkboxes, toggles etc. on the header but do not want the clicks to scroll back to the top of the table. Has anybody found a solution to prevent that or could there be an option to prevent it?

Otherwise, the lib works great and was just the thing we were looking for  :)

**Comment by jjylha** [comment]
Works great and as expected! Thank you sir 👍
