### ISSUE TITLE
Scrolling a container other than `document.body`

### ISSUE THREAD

**Issue by finkrer** [archfz/vh-sticky-table-header#7]
I've just realized a use case is not supported when we are scrolling not inside the document body but inside an inner element. I have a full-viewport modal overlay with a table inside of it. It looks and behaves like a separate page but is in fact just a container sitting on top of a previous page.

Right now there is no way to specify a different target container for position calculations and scroll events. It could be done by optionally passing a ref, like you can currently specify the table container and such.

**Comment by archfz** [comment]
Release in 1.5.0
